### ISSUE TITLE
gradle build fails at buildDockerImage task

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [otrosien/sonar-perl#13]
Hello,

when build the plugin, sonar plugin build correctly but the docker part end in error cheers

Sonar Plugin Created.
:sonar-perl-plugin:assemble
:sonar-perl-plugin:compileTestJava
:sonar-perl-plugin:processTestResources
:sonar-perl-plugin:testClasses
:sonar-perl-plugin:test
:sonar-perl-plugin:check
:sonar-perl-plugin:copyDockerfile
:sonar-perl-plugin:copyDockerTargetArtifacts
:sonar-perl-plugin:buildDockerImage
Building image using context '/home/bmortier/tmp/sonar-perl/sonar-perl-plugin/build/docker'.
Using tag 'otrosien/sonar-perl:latest' for image.
[pool-2-thread-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.newsclub.net.unix.AFUNIXSocketException) caught when processing request: Aucun fichier ou dossier de ce type
[pool-2-thread-1] INFO org.apache.http.impl.execchain.RetryExec - Retrying request
[pool-2-thread-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.newsclub.net.unix.AFUNIXSocketException) caught when processing request: Aucun fichier ou dossier de ce type
[pool-2-thread-1] INFO org.apache.http.impl.execchain.RetryExec - Retrying request
[pool-2-thread-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.newsclub.net.unix.AFUNIXSocketException) caught when processing request: Aucun fichier ou dossier de ce type
[pool-2-thread-1] INFO org.apache.http.impl.execchain.RetryExec - Retrying request
[pool-2-thread-1] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.newsclub.net.unix.AFUNIXSocketException: Aucun fichier ou dossier de ce type (socket: /run/docker.sock)
        at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
        at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:134)
        at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:97)
        at com.github.dockerjava.jaxrs.ApacheUnixSocket.connect(ApacheUnixSocket.java:64)
        at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:73)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:45)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
:sonar-perl-plugin:buildDockerImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sonar-perl-plugin:buildDockerImage'.
> java.lang.reflect.InvocationTargetException-->null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by otrosien** [comment]
`gradle build` is the full build cycle, including the creation of a docker image, which is probably not something you wanted to do, I guess. 

If you want to see the plugin in action, run it with docker-compose (see current README), or if you want to copy the plugin jar to your own SonarQube, you could just run `./gradlew sonar-perl-plugin:jar` which creates the plugin jar in `sonar-perl-plugin/build/libs/`.

HTH, Oliver

**Comment by bilbo-the-hobbit** [comment]
hello,

yes i copied the plugin to my sonar instance, just reported the bug because it was failling at docker step and wanted to give input.

Cheers

**Comment by otrosien** [comment]
Got you, I clarified this in the README.
